function gfsmart(flag)
inStrCN=char('     SMART 地震正演模拟研究工具箱','',...
    '     SMART（seismic modelling and research toolkit，SMART) MATLAB 工具包是',...
    ' 笔者在中国石油大学（华东）读硕士研究生期间所写，进行波动方程地震正演模拟与研',...
    ' 究的程序集。作为一个开源工具包，SMART旨在为那些刚刚接触地震正演模拟的同学、',...
    ' 研究者提供一个友善的平台作为入门之用。限于笔者水平，该工具包没有提供功能完备',...
    ' 的正演模拟程序，但是内有大量的例子以供参考。笔者分享SMART的初衷是，希望使用者',...
    ' 能够快捷地构建自己的程序，测试新的算法，进行程序原型设计。本说明文档简单介绍',...
    ' SMART的主要部分以及如何利用SMART进行波动方程的求解，主要包括数据读写、绘图显',...
    ' 示、差分函数、子波函数以及GPU加速等相关内容。','',...
    '     笔者在中国石油大学（华东）攻读硕士研究生期间，师从杜启振教授。杜老师治学',...
    ' 严谨，一丝不苟的精神为笔者敬佩不已。在这里，笔者要郑重感谢杜老师在学习、生活',...
    ' 和工作上的关心与指导。若没有杜老师的支持与鼓励，笔者是很难完成这项工作的。',...
    ' 此外，还要对弹性波地震勘探研究组（Elastic wave exploration project, EWEP）',...
    ' 各位师兄弟的帮助表示衷心的感谢。','',...
    '     SMART的后续维护与更新由笔者与EWEP研究组共同负责，完善其功能。限于作者水平，',...
    ' 难免存在疏漏、不妥以及错误之处，敬请批评指正。如果您有什么问题，建议或者任何与',...
    ' SMART有关的想法，希望您能与作者分享，完善SMART。作者邮箱：chf_guo@163.com;',...
    ' multi-wave@163.com。','',...
    '                                                       郭成锋',...
    '                                                   2016年10月22日');
inStrEN=char('     SMART（seismic modelling and research toolkit，SMART)','',...
    '    SMART is a simple but useful toolbox for numerical wave prpogation',... 
    ' modelling.The primary aim of SMART is to provide some basic functions',...
    ' for researchers to build their programes easily.','',...
    '    SMART stems from some subfunctions I wrote during my Master research',...
    ' at China University of Petroleum (East China). There are many modelling',...
    ' examples in SMART, but note that SMART is not a complete, mature seis-',...
    ' mic modelling software. In this introduction, I will show you how to ',...
    ' use SMART to write modeing programe.if you find any problems, please',...
    ' connect the Author(s): chf_guo@163.com','','',...
    '                                                     Guo Chengfeng',...
    '                                                   October 22, 2016');
if nargin<1
    disp(inStrEN);
    smartdoc();
else
    disp(inStrCN);
end
