function plotp(inputdata)
% This is a plot function generated by gfplot, automatically
% Usage: plotp(inputdata)
%
% Author: Guo C.F.
% Date: 19-Jan-2017

handles.data=inputdata;
handles.pos=[0.240625,0.235556,0.369375,0.622222];
[handles.ns,handles.ntr]=size(handles.data);
handles.icolor='g';
handles.isfillup='y';
handles.iszero=1;
handles.isreverse=1;
handles.iscolorbar=0;
handles.igain=1.500000;
handles.axesPro.FontNamePopupmenu=1;
handles.axesPro.WeightPopupmenu=1;
handles.axesPro.AnglePopupmenu=1;
handles.axesPro.xLabelEdit='Distance(Km)';
handles.axesPro.yLabelEdit='Depth(Km)';
% handles.axesPro.xLabelEdit='Grid';
% handles.axesPro.yLabelEdit='Grid';
handles.axesPro.xySizePopupmenu=18;
handles.axesPro.fillupPopupmenu=2;
handles.axesPro.xStartEdit=0.000000;
handles.axesPro.yStartEdit=0.000000;
handles.axesPro.xStepEdit=0.01;
handles.axesPro.yStepEdit=0.01;
handles.axesPro.LineWidthEdit=1.500000;
handles.axesPro.mainSizePopupmenu=14;
handles.axesPro.barLabelEdit='Amplitude';
handles.axesPro.barSizePopupmenu=12;
handles.axesPro.titleSizePopupmenu=12;
handles.axesPro.titleEdit=[];
gfplotmp(handles);
